// BLIND/client/components/main/BestBoardCard.vue
<template>
  <div class="best board-card">
    <div class="head">
      <div class="title-side">
        <div class="board-icon"></div>
        <h2>토픽 베스트</h2>
      </div>
      <nuxt-link
        :to="{
          name: 'topics-id',
          params: {
            id: '토픽-베스트',
          },
        }"
        >더보기 ></nuxt-link
      >
    </div>
    <div class="body">
      <ul class="article-list">
        <li v-for="a in articleList" :key="a._id">
          <div class="article-title">
            <span class="board-tag">{{ boardList[a.board] }}</span>
            <span>{{ a.title }}</span>
          </div>
          <div class="count-display">
            <div class="count-item">
              <ThumbsUpIcon size="1x" class="icon" />
              <span>{{ a.thumbupCount }}</span>
            </div>
            <div class="count-item">
              <MessageCircleIcon size="1x" class="icon" />
              <span>{{ a.commentCount }}</span>
            </div>
          </div>
        </li>
      </ul>
    </div>
  </div>
</template>
<script>
import { ThumbsUpIcon, MessageCircleIcon } from "vue-feather-icons";
export default {
  props: {
    articleList: {
      type: Array,
      default: [],
    },
  },
  components: {
    MessageCircleIcon,
    ThumbsUpIcon,
  },
  data() {
    return {
      boardList: {},
    };
  },
  created() {
    this.getBoardList();
  },
  methods: {
    async getBoardList() {
      const data = await this.$api.$get("/board/list");
      if (!Array.isArray(data)) {
        return;
      }
      data.forEach((v) => {
        this.boardList[v._id] = v.title;
      });
    },
  },
};
</script>
<style lang="scss">
.board-tag {
  font-size: 12px;
  padding: 2px;
  border: solid 1px #94969b;
  color: #94969b;
  margin-right: 5px;
  position: relative;
  top: -2px;
}
</style>

// insta/src/components/organisms/Main/BestBoardCard.jsx
import React, { useEffect, useState } from "react";
import { FiThumbsUp } from "react-icons/fi";
import { BiComment } from "react-icons/bi";
import { AiOutlineCrown } from "react-icons/ai";
import { Link } from "react-router-dom";
import styled from "styled-components";
import {
  ArticleList,
  ArticleTitle,
  BoardIcon,
  Body,
  CountDisplay,
  CountItem,
  Head,
  TitleSide,
  Wrapper,
} from "../../atoms/board";
import { getBoardList } from "../../../apis/board";

const BestBoardCard = ({ title, slug, articleList }) => {
  const [boardList, setBoardList] = useState({});
  useEffect(() => {
    (async () => {
      const data = await getBoardList();
      //console.log(data);
      data.forEach((v) => {
        setBoardList({ ...boardList, [v._id]: v.title });
      });
    })();
  }, []);
  return (
    <Wrapper>
      <Head>
        <TitleSide>
          <AiOutlineCrown size="30" />
          <h2>알럼 베스트</h2>
        </TitleSide>
        <Link to="/">더보기 +</Link>
      </Head>
      <Body>
        <ArticleList>
          {articleList.map((a) => (
            <li key={a.id + a.slug}>
              <ArticleTitle>
                <BoardTag>{boardList[a.board]}</BoardTag>
                <span>{a.title}</span>
              </ArticleTitle>
              <CountDisplay>
                <CountItem>
                  <FiThumbsUp size="16" className="icon" />
                  <span>{a.thumbupCount}</span>
                </CountItem>
                <CountItem>
                  <BiComment size="16" className="icon" />
                  <span>{a.commentCount}</span>
                </CountItem>
              </CountDisplay>
            </li>
          ))}
        </ArticleList>
      </Body>
    </Wrapper>
  );
};

const BoardTag = styled.span`
  position: relative;
  top: -2px;
  margin-right: 6px;
  padding: 2px;
  font-size: 12px;

  color: #94969b;
  border: solid 1px #94969b;
`;

export default BestBoardCard;
